[phases.setup]
nixPkgs = ["python310", "nodejs-18_x"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "cd web && npm install"
]

[phases.build]
cmds = [
    "cd web && npm run build"
]

[start]
cmd = "python start.py"
