[phases.setup]
nixPkgs = ["nodejs_18", "python310", "python310Packages.pip"]

[phases.install]
cmds = [
  "npm install --legacy-peer-deps",
  "python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "gunicorn api:app --bind 0.0.0.0:$PORT"
