[phases.setup]
nixPkgs = ["nodejs", "python310", "python310Packages.pip", "python310Packages.setuptools"]

[phases.install]
cmds = [
  "npm install --legacy-peer-deps",
  "python3 -m pip install --upgrade pip setuptools wheel",
  "python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "python3 -m gunicorn api:app --bind 0.0.0.0:$PORT"
