[phases.setup]
nixPkgs = [
  "nodejs", 
  "python310",
  "python310Packages.flask",
  "python310Packages.flask-cors",
  "python310Packages.gunicorn"
]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "gunicorn api:app --bind 0.0.0.0:$PORT"
