[phases.setup]
nixPkgs = ["nodejs", "python310"]

[phases.install]
cmds = [
  "npm install --legacy-peer-deps",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "gunicorn api:app --bind 0.0.0.0:$PORT"
