[phases.setup]
nixPkgs = ["nodejs", "python310", "python310Packages.pip"]

[phases.install]
cmds = [
  "npm install",
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "gunicorn api:app --bind 0.0.0.0:$PORT"
