[build]
builder = "NIXPACKS"
nixpacksPlan = """
{
  "phases": {
    "setup": {
      "nixPkgs": ["nodejs_18", "python310"]
    },
    "install": {
      "cmds": [
        "npm install --legacy-peer-deps",
        "pip install -r requirements.txt"
      ]
    },
    "build": {
      "cmds": ["npm run build"]
    }
  },
  "start": {
    "cmd": "gunicorn api:app --bind 0.0.0.0:$PORT"
  }
}
"""

[deploy]
startCommand = "gunicorn api:app --bind 0.0.0.0:$PORT"
